# Generated by Django 5.2.3 on 2025-07-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
