# Generated by Django 5.2.4 on 2025-07-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_order_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Big Meals', 'Big Meals'), ('Drinks', 'Drinks'), ('Desserts', 'Desserts')], default='Big Meals', max_length=20),
        ),
    ]
